export const enum GAME_TYPES {
    SELECT_SUIT_FOR_TILE,
    SELECT_NAME_FOR_TILE,
    SELECT_TILE_FOR_NAME,
    WRITE_NAME_FOR_TILE,
}

export const enum INCLUDED_TILES {
    MAN,
    PIN,
    SOU,
    WINDS,
    DRAGONS,
}

export const SUITS = [
    INCLUDED_TILES.MAN,
    INCLUDED_TILES.PIN,
    INCLUDED_TILES.SOU,
];
export const HONORS = [INCLUDED_TILES.WINDS, INCLUDED_TILES.DRAGONS];
